add_executable(std_vibe_unit_tests
  "${CMAKE_CURRENT_SOURCE_DIR}/array_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/any_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/atomic_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/bit_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/barrier_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/bitset_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cassert_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cctype_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/charconv_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cfenv_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/chrono_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cinttypes_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cmath_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cerrno_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/clocale_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/codecvt_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/complex_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cstring_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cstdarg_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cstdio_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/ctime_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cuchar_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/csignal_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/csetjmp_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cwchar_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cwctype_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/ranges_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/algorithms_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cstdlib_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cstddef_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cstdint_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/exception_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/flat_map_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/flat_set_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/filesystem_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/fstream_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/format_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/forward_list_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/future_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/functional_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/generator_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/hazard_pointer_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/hive_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/iomanip_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/inplace_vector_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/initializer_list_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/iterator_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/ios_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/iosfwd_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/iostream_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/istream_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/latch_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/list_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/linalg_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/locale_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/limits_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/map_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/mdspan_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/numbers_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/numeric_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/new_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/optional_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/random_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/rcu_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/queue_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/regex_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/set_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/shared_mutex_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/source_location_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/span_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/simd_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/stack_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/streambuf_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/strstream_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/syncstream_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/stdfloat_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/string_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/string_view_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/text_encoding_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/thread_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/ostream_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/print_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/spanstream_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/sstream_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/typeindex_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/tuple_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/unordered_map_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/unordered_set_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/utility_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/valarray_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/vector_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/variant_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/typeinfo_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/version_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/concepts_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/deque_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/debugging_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/expected_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/stacktrace_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/stop_token_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/stdexcept_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/system_error_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/memory_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/memory_resource_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/scoped_allocator_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/semaphore_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/meta_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/mutex_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/ratio_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/type_traits_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/execution_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/cfloat_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/climits_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/compare_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/condition_variable_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/contracts_test.cpp"
  "${CMAKE_CURRENT_SOURCE_DIR}/coroutine_test.cpp"
)

set_property(TARGET std_vibe_unit_tests PROPERTY CXX_STANDARD 23)
target_compile_options(std_vibe_unit_tests PRIVATE /std:c++latest)

find_package(GTest REQUIRED)
target_link_libraries(std_vibe_unit_tests PRIVATE GTest::gtest GTest::gtest_main)
include(GoogleTest)
